module.exports = {
  // AB Media
  athleticbusiness: {
    name: 'Athletic Business',
    domain: 'athleticbusiness.com',
    project: 'AB Media',
    accountKey: 'abm',
    groupKey: 'ab',
    tenantKey: 'abm_ab',
    replicaSet: 'aerilon',
    logo: 'https://cdn.baseplatform.io/files/base/abm/ab/logo.png',
    dns: 'external',
    hasContainer: true,
  },
  aquamagazine: {
    name: 'Aqua Magazine',
    domain: 'aquamagazine.com',
    project: 'AB Media',
    accountKey: 'abm',
    groupKey: 'am',
    tenantKey: 'abm_am',
    replicaSet: 'aerilon',
    logo: 'https://cdn.baseplatform.io/files/base/abm/am/logo.png',
    dns: 'external',
    hasContainer: false,
  },
  woodfloorbusiness: {
    name: 'Wood Floor Business',
    domain: 'woodfloorbusiness.com',
    project: 'AB Media',
    accountKey: 'abm',
    groupKey: 'wfb',
    tenantKey: 'abm_wfb',
    replicaSet: 'aerilon',
    logo: 'https://cdn.baseplatform.io/files/base/abm/wfb/logo.png',
    dns: 'external',
    hasContainer: false,
  },

  // AC Business Media
  // dmnews: {
  //   name: 'DM News',
  //   domain: 'dmnews.com',
  //   project: 'AC Business Media',
  //   accountKey: 'acbm',
  //   groupKey: 'dmn',
  //   tenantKey: 'acbm_dmn',
  //   replicaSet: 'caprica',
  //   logo: 'https://cdn.baseplatform.io/files/base/acbm/dmn/image/static/logo/site_logo_white.png',
  // },
  // greenindustrypros: {
  //   name: 'Green Industry Pros',
  //   domain: 'greenindustrypros.com',
  //   project: 'AC Business Media',
  //   accountKey: 'acbm',
  //   groupKey: 'gip',
  //   tenantKey: 'acbm_gip',
  //   replicaSet: 'caprica',
  //   logo: 'https://cdn.baseplatform.io/files/base/acbm/gip/image/static/logo/site_logo.png',
  // },
  forconstructionpros: {
    name: 'For Construction Pros',
    domain: 'forconstructionpros.com',
    project: 'AC Business Media',
    accountKey: 'acbm',
    groupKey: 'fcp',
    tenantKey: 'acbm_fcp',
    replicaSet: 'caprica',
    logo: 'https://cdn.baseplatform.io/files/base/acbm/fcp/image/static/logo/site_logo.png',
    hasContainer: false,
  },
  // foodlogistics: {
  //   name: 'Food Logistics',
  //   domain: 'foodlogistics.com',
  //   project: 'AC Business Media',
  //   accountKey: 'acbm',
  //   groupKey: 'fl',
  //   tenantKey: 'acbm_fl',
  //   replicaSet: 'caprica',
  //   logo: 'https://cdn.baseplatform.io/files/base/acbm/fl/image/static/logo/site_logo.png'
  // },
  // oemoffhighway: {
  //   name: 'OEM Off Highway',
  //   domain: 'oemoffhighway.com',
  //   project: 'AC Business Media',
  //   accountKey: 'acbm',
  //   groupKey: 'ooh',
  //   tenantKey: 'acbm_ooh',
  //   replicaSet: 'caprica',
  //   logo: 'https://cdn.baseplatform.io/files/base/acbm/ooh/image/static/logo/site_logo.png',
  // },
  // sdcexec: {
  //   name: 'Supply & Demand Chain Executive',
  //   domain: 'sdcexec.com',
  //   project: 'AC Business Media',
  //   accountKey: 'acbm',
  //   groupKey: 'sdce',
  //   tenantKey: 'acbm_sdce',
  //   replicaSet: 'caprica',
  //   logo: 'https://cdn.baseplatform.io/files/base/acbm/sdce/image/static/logo/site_logo.png',
  // },

  // AS3
  // baseplatform: {
  //   name: 'Base Platform',
  //   domain: 'baseplatform.io',
  //   project: 'AS3',
  //   accountKey: 'as3',
  //   groupKey: 'baseplatform',
  //   tenantKey: 'as3_baseplatform',
  //   replicaSet: 'picon',
  //   logo: 'https://cdn.baseplatform.io/files/base/as3/baseplatform/image/static/base-logo.png',
  // },
  // clarity: {
  //   name: 'Clarity',
  //   domain: 'clarity.endeavorb2b.com',
  //   project: 'AS3',
  //   accountKey: 'as3',
  //   groupKey: 'clarity',
  //   tenantKey: 'as3_clarity',
  //   replicaSet: 'picon',
  // },

  // Bizbash Media, LLC
  // bizbash: {
  //   name: 'BizBash',
  //   domain: 'bizbash.com',
  //   project: 'BizBash',
  //   accountKey: 'bizbash',
  //   groupKey: 'bzb',
  //   tenantKey: 'bizbash_bzb',
  //   replicaSet: 'caprica',
  //   logo: 'https://cdn.baseplatform.io/files/base/as3/bizbash/image/static/site-logo.png',
  // },

  // Carey Media
  // thepitchkc: {
  //   name: 'The Pitch',
  //   domain: 'thepitchkc.com',
  //   project: 'Carey Media',
  //   accountKey: 'careymedia',
  //   groupKey: 'kcp',
  //   tenantKey: 'scomm_kcp',
  //   replicaSet: 'caprica',
  //   logo: 'https://cdn.thepitchkc.com/files/base/scomm/kcp/image/static/logo/kcp-large-red.png',
  // },

  // Cygnus Business Media
  // aviationpros: {
  //   name: 'Aviation Pros',
  //   domain: 'aviationpros.com',
  //   project: 'Cygnus Business Media',
  //   accountKey: 'ebm',
  //   groupKey: 'cavc',
  //   tenantKey: 'cygnus_cavc',
  //   replicaSet: 'picon',
  //   logo: 'https://cdn.baseplatform.io/files/base/cygnus/cavc/image/static/logo/site_logo.png',
  // },
  // cpapracticeadvisor: {
  //   name: 'CPA Practice Advisor',
  //   domain: 'cpapracticeadvisor.com',
  //   project: 'Cygnus Business Media',
  //   accountKey: 'ebm',
  //   groupKey: 'cpa',
  //   tenantKey: 'cygnus_cpa',
  //   replicaSet: 'picon',
  //   logo: 'https://cdn.cpapracticeadvisor.com/files/base/cygnus/cpa/image/static/logo/site_logo_white.png',
  // },
  // firehouse: {
  //   name: 'Firehouse',
  //   domain: 'firehouse.com',
  //   project: 'Cygnus Business Media',
  //   accountKey: 'ebm',
  //   groupKey: 'fhc',
  //   tenantKey: 'cygnus_fhc',
  //   replicaSet: 'picon',
  //   logo: 'https://cdn.firehouse.com/files/base/cygnus/fhc/image/static/logo/site_logo.png',
  // },
  // locksmithledger: {
  //   name: 'Locksmith Ledger',
  //   domain: 'locksmithledger.com',
  //   project: 'Cygnus Business Media',
  //   accountKey: 'ebm',
  //   groupKey: 'll',
  //   tenantKey: 'cygnus_ll',
  //   replicaSet: 'picon',
  //   logo: 'https://cdn.locksmithledger.com/files/base/cygnus/ll/image/static/logo/lsl.png',
  // },
  // masstransitmag: {
  //   name: 'Mass Transit Magazine',
  //   domain: 'masstransitmag.com',
  //   project: 'Cygnus Business Media',
  //   accountKey: 'ebm',
  //   groupKey: 'mass',
  //   tenantKey: 'cygnus_mass',
  //   replicaSet: 'picon',
  //   logo: 'https://cdn.masstransitmag.com/files/base/cygnus/mass/image/static/logo/site_logo.png',
  // },
  officer: {
    name: 'Officer',
    domain: 'officer.com',
    project: 'Cygnus Business Media',
    accountKey: 'ebm',
    groupKey: 'ofcr',
    tenantKey: 'cygnus_ofcr',
    replicaSet: 'picon',
    logo: 'https://cdn.officer.com/files/base/cygnus/ofcr/image/static/logo/site_logo.png',
    hasContainer: true,

  },
  // securityinfowatch: {
  //   name: 'Security Info Watch',
  //   domain: 'securityinfowatch.com',
  //   project: 'Cygnus Business Media',
  //   accountKey: 'ebm',
  //   groupKey: 'siw',
  //   tenantKey: 'cygnus_siw',
  //   replicaSet: 'picon',
  //   logo: 'https://cdn.securityinfowatch.com/files/base/cygnus/siw/image/static/logo/site_logo_red_on_black.png',
  // },
  // vendingmarketwatch: {
  //   name: 'Vending Market Watch',
  //   domain: 'vendingmarketwatch.com',
  //   project: 'Cygnus Business Media',
  //   accountKey: 'ebm',
  //   groupKey: 'vmw',
  //   tenantKey: 'cygnus_vmw',
  //   replicaSet: 'picon',
  //   logo: 'https://cdn.baseplatform.io/files/base/cygnus/vmw/image/static/logo/vending.png',
  // },
  // vehicleservicepros: {
  //   name: 'Vehicle Service Pros',
  //   domain: 'vehicleservicepros.com',
  //   project: 'Cygnus Business Media',
  //   accountKey: 'ebm',
  //   groupKey: 'vspc',
  //   tenantKey: 'cygnus_vspc',
  //   replicaSet: 'picon',
  //   logo: 'https://cdn.vehicleservicepros.com/files/base/cygnus/vspc/image/static/logo/vsp.png',
  // },

  // Endeavor Business Media
  evaluationengineering: {
    name: 'Evaluation Engineering',
    domain: 'evaluationengineering.com',
    project: 'Endeavor Business Media',
    accountKey: 'ebm',
    groupKey: 'ee',
    tenantKey: 'ebm_ee',
    replicaSet: 'picon',
    logo: 'https://cdn.evaluationengineering.com/files/base/ebm/ee/image/static/logo/site_logo_bare.png',
    hasContainer: true,
  },
  // flowcontrolnetwork: {
  //   name: 'Flow Control Network',
  //   domain: 'flowcontrolnetwork.com',
  //   project: 'Endeavor Business Media',
  //   accountKey: 'ebm',
  //   groupKey: 'fcn',
  //   tenantKey: 'ebm_fcn',
  //   replicaSet: 'picon',
  //   logo: 'https://cdn.evaluationengineering.com/files/base/ebm/ee/image/static/logo/site_logo_bare.png',
  // },
  // forresternetwork: {
  //   name: 'Forrester Network',
  //   domain: 'forresternetwork.com',
  //   project: 'Endeavor Business Media',
  //   accountKey: 'ebm',
  //   groupKey: 'frn',
  //   tenantKey: 'ebm_frn',
  //   replicaSet: 'picon',
  //   logo: 'https://cdn.baseplatform.io/files/base/ebm/frn/image/static/logo/site_logo.png',
  // },
  // hcinnovationgroup: {
  //   name: 'Healthcare Innovation',
  //   domain: 'hcinnovationgroup.com',
  //   project: 'Endeavor Business Media',
  //   accountKey: 'ebm',
  //   groupKey: 'hci',
  //   tenantKey: 'ebm_hci',
  //   replicaSet: 'picon',
  //   logo: 'https://cdn.hcinnovationgroup.com/files/base/ebm/hci/image/static/logo/site_logo.png',
  // },
  // hpnonline: {
  //   name: 'Healthcare Purchasing News',
  //   domain: 'hpnonline.com',
  //   project: 'Endeavor Business Media',
  //   accountKey: 'ebm',
  //   groupKey: 'hpn',
  //   tenantKey: 'ebm_hpn',
  //   replicaSet: 'picon',
  //   logo: 'https://cdn.hpnonline.com/files/base/ebm/hpn/image/static/logo/site_logo_white.png',
  // },
  // 'mlo-online': {
  //   name: 'Medical Laboratory Observer',
  //   domain: 'mlo-online.com',
  //   project: 'Endeavor Business Media',
  //   accountKey: 'ebm',
  //   groupKey: 'mlo',
  //   tenantKey: 'ebm_mlo',
  //   replicaSet: 'picon',
  //   logo: 'https://cdn.mlo-online.com/files/base/ebm/mlo/image/static/logo/site_logo.png',
  // },
  // processingmagazine: {
  //   name: 'Processing Magazine',
  //   domain: 'processingmagazine.com',
  //   project: 'Endeavor Business Media',
  //   accountKey: 'ebm',
  //   groupKey: 'pm',
  //   tenantKey: 'ebm_pm',
  //   replicaSet: 'picon',
  //   logo: 'https://cdn.baseplatform.io/files/base/ebm/pm/image/static/site_logo.png',
  // },
  plasticsmachinerymagazine: {
    name: 'Plastics Machinery Magazine',
    domain: 'plasticsmachinerymagazine.com',
    project: 'Endeavor Business Media',
    accountKey: 'ebm',
    groupKey: 'pmm',
    tenantKey: 'ebm_pmm',
    replicaSet: 'picon',
    logo: 'https://cdn.baseplatform.io/files/base/ebm/pmm/image/static/site_logo.png',
    hasContainer: true,
  },
  // watertechonline: {
  //   name: 'Water Technology',
  //   domain: 'watertechonline.com',
  //   project: 'Endeavor Business Media',
  //   accountKey: 'ebm',
  //   groupKey: 'wto',
  //   tenantKey: 'ebm_wto',
  //   replicaSet: 'picon',
  //   logo: 'https://cdn.baseplatform.io/files/base/ebm/wto/image/static/site_logo.png',
  // },

  // Euclid Media Group
  clevescene: {
    name: 'Cleveland Scene',
    domain: 'clevescene.com',
    project: 'Euclid Media Group',
    accountKey: 'euclid',
    groupKey: 'cs',
    tenantKey: 'euclid_cs',
    replicaSet: 'caprica',
    logo: 'https://cdn.baseplatform.io/files/base/euclid/cs/logo.png',
    dns: 'external',
    hasContainer: false,
  },
  metrotimes: {
    name: 'Detroit Metro Times',
    domain: 'metrotimes.com',
    project: 'Euclid Media Group',
    accountKey: 'euclid',
    groupKey: 'dmt',
    tenantKey: 'euclid_dmt',
    replicaSet: 'caprica',
    logo: 'https://cdn.baseplatform.io/files/base/euclid/dmt/logo.png',
    dns: 'external',
    hasContainer: false,
  },
  orlandoweekly: {
    name: 'Orlando Weekly',
    domain: 'orlandoweekly.com',
    project: 'Euclid Media Group',
    accountKey: 'euclid',
    groupKey: 'ow',
    tenantKey: 'euclid_ow',
    replicaSet: 'caprica',
    logo: 'https://cdn.baseplatform.io/files/base/euclid/ow/logo.png',
    dns: 'external',
    hasContainer: false,
  },
  sacurrent: {
    name: 'San Antonio Current',
    domain: 'sacurrent.com',
    project: 'Euclid Media Group',
    accountKey: 'euclid',
    groupKey: 'sac',
    tenantKey: 'euclid_sac',
    replicaSet: 'caprica',
    logo: 'https://cdn.baseplatform.io/files/base/euclid/sac/logo.png',
    dns: 'external',
    hasContainer: false,
  },
  riverfronttimes: {
    name: 'River Front Times',
    domain: 'riverfronttimes.com',
    project: 'Euclid Media Group',
    accountKey: 'euclid',
    groupKey: 'rft',
    tenantKey: 'euclid_rft',
    replicaSet: 'caprica',
    logo: 'https://cdn.baseplatform.io/files/base/euclid/rft/logo.png',
    dns: 'external',
    hasContainer: false,
  },
  outinsa: {
    name: 'OUT in SA',
    domain: 'outinsa.com',
    project: 'Euclid Media Group',
    accountKey: 'euclid',
    groupKey: 'osa',
    tenantKey: 'euclid_osa',
    replicaSet: 'caprica',
    logo: 'https://cdn.baseplatform.io/files/base/euclid/osa/logo.png',
    dns: 'external',
    hasContainer: false,
  },
  outinstl: {
    name: 'OUT in STL',
    domain: 'outinstl.com',
    project: 'Euclid Media Group',
    accountKey: 'euclid',
    groupKey: 'ostl',
    tenantKey: 'euclid_ostl',
    replicaSet: 'caprica',
    logo: 'https://cdn.baseplatform.io/files/base/euclid/ostl/logo.png',
    dns: 'external',
    hasContainer: false,
  },
  // citybeat: {
  //   name: 'City Beat',
  //   domain: 'citybeat.com',
  //   project: 'Euclid Media Group',
  //   accountKey: 'euclid',
  //   groupKey: 'cb',
  //   tenantKey: 'scomm_cb',
  //   replicaSet: 'caprica',
  //   logo: 'https://cdn.citybeat.com/files/base/scomm/cb/image/static/logo/site_logo.png',
  // },
  // cltampa: {
  //   name: 'Creative Loafing: Tampa',
  //   domain: 'cltampa.com',
  //   project: 'Euclid Media Group',
  //   accountKey: 'euclid',
  //   groupKey: 'cltampa',
  //   tenantKey: 'scomm_cltampa',
  //   replicaSet: 'caprica',
  //   logo: 'https://cdn.cltampa.com/files/base/scomm/cltampa/image/static/logo/cltampa-large-light.png',
  // },

  // FW Publishing
  // nfocusnashville: {
  //   name: 'nFocus Nashville',
  //   domain: 'nfocusnashville.com',
  //   project: 'FW Publishing',
  //   accountKey: 'fwp',
  //   groupKey: 'nfn',
  //   tenantKey: 'scomm_nfn',
  //   replicaSet: 'caprica',
  //   logo: 'https://cdn.nfocusnashville.com/files/base/scomm/nfn/image/static/logo/site_logo.jpg',
  // },
  // nashvillescene: {
  //   name: 'Nashville Scene',
  //   domain: 'nashvillescene.com',
  //   project: 'FW Publishing',
  //   accountKey: 'fwp',
  //   groupKey: 'nvs',
  //   tenantKey: 'scomm_nvs',
  //   replicaSet: 'caprica',
  //   logo: 'https://cdn.nashvillescene.com/files/base/scomm/nvs/image/static/logo/nvs-large-red.png',
  // },
  // nashvillepost: {
  //   name: 'Nashville Post',
  //   domain: 'nashvillepost.com',
  //   project: 'FW Publishing',
  //   accountKey: 'fwp',
  //   groupKey: 'nvp',
  //   tenantKey: 'scomm_nvp',
  //   replicaSet: 'caprica',
  //   logo: 'https://cdn.nashvillepost.com/files/base/scomm/nvp/image/static/logo/site_logo.png',
  // },

  // Industrial Media Group
  // cannabisequipmentnews: {
  //   name: 'Cannabis Equipment News',
  //   domain: 'cannabisequipmentnews.com',
  //   project: 'Industrial Media Group',
  //   accountKey: 'indm',
  //   groupKey: 'cen',
  //   tenantKey: 'indm_cen',
  //   replicaSet: 'caprica',
  //   logo: 'https://cdn.cannabisequipmentnews.com/files/base/indm/cen/image/static/logo.jpg',
  // },
  // designdevelopmenttoday: {
  //   name: 'Design & Development Today',
  //   domain: 'designdevelopmenttoday.com',
  //   project: 'Industrial Media Group',
  //   accountKey: 'indm',
  //   groupKey: 'ddt',
  //   tenantKey: 'indm_ddt',
  //   replicaSet: 'caprica',
  //   logo: 'https://cdn.designdevelopmenttoday.com/files/base/indm/ddt/image/static/logo/site_logo.png',
  // },
  // ien: {
  //   name: 'Industrial Equipment News',
  //   domain: 'ien.com',
  //   project: 'Industrial Media Group',
  //   accountKey: 'indm',
  //   groupKey: 'ien',
  //   tenantKey: 'indm_ien',
  //   replicaSet: 'caprica',
  //   logo: 'https://s3.amazonaws.com/cygnusimages/base/rmg/ien/logo.gif',
  // },

  // PennWell Corporation
  bioopticsworld: {
    name: 'Bio Optics World',
    domain: 'bioopticsworld.com',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'bow',
    tenantKey: 'ebm_bow',
    replicaSet: 'aerilon',
    published: true,
    hasContainer: true,
    logo: 'http://base.imgix.net/files/base/pennwell/bow/logo.png',
  },
  broadbandtechreport: {
    name: 'Broadband Technology Report',
    domain: 'broadbandtechreport.com',
    logo: 'http://base.imgix.net/files/base/pennwell/btr/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'btr',
    tenantKey: 'ebm_btr',
    replicaSet: 'aerilon',
    published: true,
    hasContainer: true,
  },
  cablinginstall: {
    name: 'Cabling Installation & Maintenance',
    domain: 'cablinginstall.com',
    logo: 'http://base.imgix.net/files/base/pennwell/cim/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'cim',
    tenantKey: 'ebm_cim',
    replicaSet: 'aerilon',
    published: true,
    hasContainer: true,
  },
  dentaleconomics: {
    name: 'Dental Economics',
    domain: 'dentaleconomics.com',
    logo: 'http://base.imgix.net/files/base/pennwell/de/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'de',
    tenantKey: 'ebm_de',
    replicaSet: 'aerilon',
    published: true,
    hasContainer: true,
  },
  dentistryiq: {
    name: 'DentistryIQ',
    domain: 'dentistryiq.com',
    logo: 'http://base.imgix.net/files/base/pennwell/diq/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'diq',
    tenantKey: 'ebm_diq',
    replicaSet: 'aerilon',
    published: true,
    hasContainer: true,
  },
  'intelligent-aerospace': {
    name: 'Intelligent Aerospace',
    domain: 'intelligent-aerospace.com',
    logo: 'http://base.imgix.net/files/base/pennwell/ias/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'ias',
    tenantKey: 'ebm_ias',
    replicaSet: 'aerilon',
    published: true,
    hasContainer: true,
  },
  'industrial-lasers': {
    name: 'Industrial Laser Solutions',
    domain: 'industrial-lasers.com',
    logo: 'http://base.imgix.net/files/base/pennwell/ils/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'ils',
    tenantKey: 'ebm_ils',
    replicaSet: 'aerilon',
    published: true,
    hasContainer: true,
  },
  ledsmagazine: {
    name: 'LEDs Magazine',
    domain: 'ledsmagazine.com',
    logo: 'http://base.imgix.net/files/base/pennwell/leds/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'leds',
    tenantKey: 'ebm_leds',
    replicaSet: 'aerilon',
    published: true,
    hasContainer: true,
  },
  laserfocusworld: {
    name: 'Laser Focus World',
    domain: 'laserfocusworld.com',
    logo: 'http://base.imgix.net/files/base/pennwell/lfw/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'lfw',
    tenantKey: 'ebm_lfw',
    replicaSet: 'aerilon',
    published: true,
    hasContainer: true,
  },
  lightwaveonline: {
    name: 'Lightwave',
    domain: 'lightwaveonline.com',
    logo: 'http://base.imgix.net/files/base/pennwell/lw/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'lw',
    tenantKey: 'ebm_lw',
    replicaSet: 'aerilon',
    published: true,
    hasContainer: true,
  },
  militaryaerospace: {
    name: 'Military & Aerospace Electronics',
    domain: 'militaryaerospace.com',
    logo: 'http://base.imgix.net/files/base/pennwell/mae/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'mae',
    tenantKey: 'ebm_mae',
    replicaSet: 'aerilon',
    published: true,
    hasContainer: true,
  },
  'offshore-mag': {
    name: 'Offshore Magazine',
    domain: 'offshore-mag.com',
    logo: 'http://base.imgix.net/files/base/pennwell/os/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'os',
    tenantKey: 'ebm_os',
    replicaSet: 'aerilon',
    published: true,
    hasContainer: true,
  },
  ogj: {
    name: 'Oil & Gas Journal',
    domain: 'ogj.com',
    logo: 'http://base.imgix.net/files/base/pennwell/ogj/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'ogj',
    tenantKey: 'ebm_ogj',
    replicaSet: 'aerilon',
    hasContainer: true,
    published: false,
  },
  rdhmag: {
    name: 'Registered Dental Hygienist',
    domain: 'rdhmag.com',
    logo: 'http://base.imgix.net/files/base/pennwell/rdh/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'rdh',
    tenantKey: 'ebm_rdh',
    replicaSet: 'aerilon',
    published: true,
    hasContainer: true,
  },
  perioimplantadvisory: {
    name: 'Perio-Implant Advisory',
    domain: 'perioimplantadvisory.com',
    logo: 'http://base.imgix.net/files/base/pennwell/pia/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'pia',
    tenantKey: 'ebm_pia',
    replicaSet: 'aerilon',
    published: true,
    hasContainer: true,
  },
  'strategies-u': {
    name: 'Strategies Unlimited',
    domain: 'strategies-u.com',
    logo: 'http://base.imgix.net/files/base/pennwell/su/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'su',
    tenantKey: 'ebm_su',
    replicaSet: 'aerilon',
    published: true,
    hasContainer: true,
  },
  utilityproducts: {
    name: 'Utility Products',
    domain: 'utilityproducts.com',
    logo: 'http://base.imgix.net/files/base/pennwell/up/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'up',
    tenantKey: 'ebm_up',
    replicaSet: 'aerilon',
    published: true,
    hasContainer: true,
  },
  'vision-systems': {
    name: 'Vision Systems Design',
    domain: 'vision-systems.com',
    logo: 'http://base.imgix.net/files/base/pennwell/vsd/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'vsd',
    tenantKey: 'ebm_vsd',
    replicaSet: 'aerilon',
    published: true,
    hasContainer: true,
  },
  waterworld: {
    name: 'WaterWorld',
    domain: 'waterworld.com',
    logo: 'http://base.imgix.net/files/base/pennwell/ww/logo.png',
    project: 'PennWell Corporation',
    accountKey: 'ebm',
    groupKey: 'ww',
    tenantKey: 'ebm_ww',
    replicaSet: 'aerilon',
    published: true,
    hasContainer: true,
  },

  // PMMI Media Group
  packworld: {
    name: 'Packaging World',
    domain: 'packworld.com',
    project: 'PMMI Media Group',
    accountKey: 'pmmi',
    groupKey: 'pw',
    tenantKey: 'pmmi_pw',
    replicaSet: 'aerilon',
    logo: 'https://cdn.baseplatform.io/files/base/pmmi/pw/logo.png',
    dns: 'external',
    hasContainer: false,
  },
  automationworld: {
    name: 'Automation World',
    domain: 'automationworld.com',
    project: 'PMMI Media Group',
    accountKey: 'pmmi',
    groupKey: 'aw',
    tenantKey: 'pmmi_aw',
    replicaSet: 'aerilon',
    logo: 'https://cdn.baseplatform.io/files/base/pmmi/aw/logo.png',
    dns: 'external',
    hasContainer: false,
  },
  healthcarepackaging: {
    name: 'Healthcare Packaging',
    domain: 'healthcarepackaging.com',
    project: 'PMMI Media Group',
    accountKey: 'pmmi',
    groupKey: 'hp',
    tenantKey: 'pmmi_hp',
    replicaSet: 'aerilon',
    logo: 'https://cdn.baseplatform.io/files/base/pmmi/hp/logo.png',
    dns: 'external',
    hasContainer: false,
  },
  profoodworld: {
    name: 'Pro Food World',
    domain: 'profoodworld.com',
    project: 'PMMI Media Group',
    accountKey: 'pmmi',
    groupKey: 'pfw',
    tenantKey: 'pmmi_pfw',
    replicaSet: 'aerilon',
    logo: 'https://cdn.baseplatform.io/files/base/pmmi/pfw/logo.png',
    dns: 'external',
    hasContainer: false,
  },
  oemmagazine: {
    name: 'OEM Magazine',
    domain: 'oemmagazine.org',
    project: 'PMMI Media Group',
    accountKey: 'pmmi',
    groupKey: 'oem',
    tenantKey: 'pmmi_oem',
    replicaSet: 'aerilon',
    logo: 'https://cdn.baseplatform.io/files/base/pmmi/oem/logo.png',
    dns: 'external',
    hasContainer: false,
  },

  // Washington City Paper
  // washingtoncitypaper: {
  //   name: 'Washington City Paper',
  //   domain: 'washingtoncitypaper.com',
  //   project: 'Washington City Paper',
  //   accountKey: 'wcp',
  //   groupKey: 'wcp',
  //   tenantKey: 'scomm_wcp',
  //   replicaSet: 'caprica',
  //   logo: 'https://cdn.washingtoncitypaper.com/files/guidr/scomm/wcp/logo.png',
  // },

  // What They Think
  // printingnews: {
  //   name: 'Printing News',
  //   domain: 'printingnews.com',
  //   project: 'What They Think',
  //   accountKey: 'wtt',
  //   groupKey: 'pn',
  //   tenantKey: 'cygnus_mprc',
  //   replicaSet: 'caprica',
  //   logo: 'https://cdn.printingnews.com/files/base/cygnus/mprc/image/static/logo/site_logo.png',
  // },
};
